### ISSUE TITLE
Enhancement: new Icons (Haiku's style)

### ISSUE THREAD

**Issue by Giova84** [HaikuArchives/Beam#3]
I improved the icon theme "Stippi 32" (provided by default with Beam): I replaced the old folder icon with the one used on Haiku, I changed the "mail new" and the "mail read" icons, I updated the attachments icons and the "tofu" and "spam" icons, to make Beam look more modern and integrated to the Haiku's style.

Preview:
![2e4fr](https://user-images.githubusercontent.com/1316513/28796652-0f828510-7647-11e7-9fe0-09bbd3852a42.png)

You can download them from here as zip archive. Feel free to add these icons to Beam.
http://softwaredepot.altervista.org/haiku/upload/icons/_iconset_32_haiku.zip

**Comment by waddlesplash** [comment]
I won't have time to poke at this until the weekend; someone else is free to try to apply this in the meantime.

**Comment by Giova84** [comment]
Sorry for the noise (I am on Qupzilla and I'm unable to edit my first post):

This is the right link, since I forget to add a pair of icons.
http://softwaredepot.altervista.org/haiku/upload/icons/_iconset_32_haiku.zip

Kind regards.

**Comment by richienyhus** [comment]
I am not so sure of the mix of 2d and 3d icons.

**Comment by diversys** [comment]
[_iconset_32_haiku.zip](https://github.com/HaikuArchives/Beam/files/3353744/_iconset_32_haiku.zip)

**Comment by diversys** [comment]
@humdingerb could you please take a look?

**Comment by humdingerb** [comment]
I am looking at it and would like to propose a few changes to some of the icons. I'll upload my suggestion when I'm done. Maybe we can discuss it in the end use it as default icon theme.

**Comment by humdingerb** [comment]
Here's a screenshot with my changes: https://linx.li/beam.png

Changes compared to Giovanni's proposal:

* Check: To avoid re-using the mail icon with a small overlay too often, I used a slightly modified mail_daemon icon. As you check your inbox, the icon feel appropriate and people may already be used to it, if they come from Mail/mail_daemon.
* New: As before. A mixture of the Mail icon and modified StyledEdit icon.
* Reply/Forward: Use different coloured arrows, which are repeated in the small icons of the list view.
* Spam/Tofu: Make them not quite as fat...
* Attach (in new mail window): Use the same icon as in the list view.
* List view: use 2D icons. Use just the arrows for Reply/Forward, because they'd become too tiny if used as overlay over the regular mail icon. New/Read icons are slightly altered icons from the Haiku tree. Sent icon is taken from Haiku tree. Pending icon is a green version of zuMi's icon.
Added Priority icons, similar to Mike Larsson's iconset.

I have created the PR #13 for people to try it directly.

**Comment by diversys** [comment]
These are some nice looking icons! Definitely a huge improvement :)

**Comment by humdingerb** [comment]
Great!
Should we rename the iconset to "Default" and make it the default (I suppose that'd mean putting them into the rdefs)?
What are the thoughts on the app icon (+deskbar replicant)? Gotta say, I don't like the traditional one much. How about the Beam icons in the Haiku tree (the blue mailbox)? If people like to keep the traditional UK red one, we should try to improve it at least...

**Comment by diversys** [comment]
Yep! Sounds good. +1 to the blue mailbox.
